[build-system]
requires = [
    "setuptools==65.5.1",
    "setuptools_scm[toml]==7.0.5",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "prow-jobs-scraper"
description = "Scrape Prow for job results and export them to elasticsearch"
readme = "README.md"
keywords = ["prow"]
license = { file = "LICENSE" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "requests==2.31.0",
    "google-cloud-storage==2.14.0",
    "junitparser==3.1.1",
    "pydantic==1.10.13",
    "opensearch-py==2.4.2",
    "slack_sdk==3.26.1",
    "plotly==5.18.0",
    "kaleido==0.2.1",
    "python-dateutil==2.8.2",
    "retry==0.9.2",
    "pandas==2.1.4",
    "numpy==1.26.3",
    "mmh3==4.0.1",
]
dynamic = ["version"]

[project.scripts]
prow-jobs-scraper = "prowjobsscraper.main:main"
jobs-auto-report = "jobsautoreport.main:main"
elasticsearch-cleanup = "elasticsearch_cleanup.main:main"

[project.optional-dependencies]
test-runner = [
    "tox==4.11.4",
]
unit-tests = [
    "freezegun==1.4.0",
    "pytest==7.4.4",
    "pytest-cov==4.1.0",
    "pytest-httpserver==1.0.8",
]
coverage = [
    "coverage[toml]==7.4.0",
]
lint = [
    "black==23.12.1",
    "isort==5.13.2",
    "mypy==1.8.0",
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = clean,python3.11,report

[testenv]
usedevelop=True
commands = pytest --cov=src --cov-append --cov-report=term-missing --junitxml=junit-{envname}.xml --junit-prefix={envname} {posargs}
deps = .[unit-tests]
depends =
    {python3.11}: clean
    report: python3.11

[testenv:report]
deps = .[coverage]
skip_install = true
commands =
    coverage report
    coverage html
    coverage xml

[testenv:clean]
deps = .[coverage]
skip_install = true
commands = coverage erase
"""
